name: backend_dart
description: Backend Dart do projeto SÃ£o Paulo Stock Sync - Metro SP 2025
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  shelf: ^1.4.1 
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2     
  http_parser: ^4.0.2      
  path: ^1.9.0
  http: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
