name: spss_dart_backend
description: Backend em Dart Shelf para o SÃ£o Paulo Stock Sync
version: 0.1.0
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2

dev_dependencies:
  lints: ^4.0.0
